modLoader="javafml" #mandatory
loaderVersion="[4,)" #mandatory

license="MIT"

[[mods]] #mandatory
modId="dynamicatmosphere" #mandatory
version="${mod_version}" #mandatory
displayName="Dynamic Atmosphere" #mandatory
authors="brooswit"
description='''An atmospheric grid with server-owned material buildup and decay, synchronized to nearby clients and rendered as translucent cells. No inter-cell flow or terrain modification.'''

[[dependencies.dynamicatmosphere]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dynamicatmosphere]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"
